### ISSUE TITLE
Why not train on cnndm manually annotated dataset?

### ISSUE THREAD

**Issue by gaozhiguang** [tagoyal/factuality-datasets#1]
Hi, very nive work.
A little bit confused is why don't you train the model you mentioned in this article on cnndm's manually annotated dataset.Is it because there is no such data?

In addition, because I need a fact model to evaluate my summary, it seems that there is no cnndm factuality evaluation model trained on the Synthetic Dataset in the link you gave. Can you provide it to me?

thanks.

**Comment by tagoyal** [comment]
The human annotated data for CNNDM was quite small (around 500 ex if i remember correctly) and also had very unbalanced label distribution.

Models: I uploaded the models to the google drive.

**Comment by gaozhiguang** [comment]
Thanks a lot.
