### ISSUE TITLE
preprocessed CNNDM manually annotated dataset

### ISSUE THREAD

**Issue by vivald99** [tagoyal/factuality-datasets#2]
Hi, thanks for the great work!

I was able to execute the **DAE model** for _Xsum-human_ (using the preprocessed files `factuality_models_datasets/training_datasets/Xsum-human`).
Please, could you also provide the _CNNDM-human_ in a preprocessed form? Or the script used to generate the preprocessed inputs for the DAE model?

Thank you again.

**Comment by tagoyal** [comment]
Hi,
thanks for pointing this out! I have uploaded the human annotated test data (results in the paper reported on this) to the google drive.
factuality_models_datasets/training_datasets/CNNDM-human
