### ISSUE TITLE
Script for reading manually annotated data

### ISSUE THREAD

**Issue by manzar96** [tagoyal/factuality-datasets#9]
Hello,

I can't find the script for reading the manually annottated data. The uploaded files on the drive are in ".numbers" format which makes it difficult to be read by users using different OS.
Can you please provide the script for reading these data or to provide the data in another more user friendly format?

**Comment by tagoyal** [comment]
I've uploaded tsv versions of the two files in the same folder. 

Alternatively, recent work provides the data (along with a bunch of other datasets) in a more readable format: https://github.com/Liyan06/AggreFact
